export const ORDER_SAVE_REQUEST='ORDER_SAVE_REQUEST'
export const ORDER_SAVE_SUCCESS='ORDER_SAVE_SUCCESS'
export const ORDER_SAVE_FAILED='ORDER_SAVE_FAILED'

export const ORDER_DETAILS_SUCCESS='ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_REQUEST='ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED'


export const ORDER_PAYMENT_UPDATE_REQUEST='ORDER_PAYMENT_UPDATE_REQUEST'
export const ORDER_PAYMENT_UPDATE_SUCCESS='ORDER_PAYMENT_UPDATE_SUCCESS'
export const ORDER_PAYMENT_UPDATE_FAILED='ORDER_PAYMENT_UPDATE_FAILED'
export const ORDER_PAMENT_UPDATE_RESET='ORDER_PAMENT_UPDATE_RESET'

export const GET_MY_ORDERS_REQUEST='GET_MY_ORDERS_REQUEST'
export const GET_MY_ORDERS_SUCCESS='GET_MY_ORDERS_SUCCESS'
export const GET_MY_ORDERS_FAILED='GET_MY_ORDERS_FAILED'

export const GET_ALL_ORDERS_REQUEST='GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS='GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILED='GET_ALL_ORDERS_FAILED'