export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'
export const USER_LOGOUT='USER_LOGOUT'

export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'

export const USER_DETAIL_REQUEST="USER_DETAIL_REQUEST"
export const USER_DETAIL_SUCCESS="USER_DETAIL_SUCCESS"
export const USER_DETAIL_FAILED="USER_DETAIL_FAILED"

export const USER_UPDATE_PROFILE_REQUEST="USER_UPDATE_PROFILE_REQUEST"
export const USER_UPDATE_PROFILE_SUCCESS="USER_UPDATE_PROFILE_SUCCESS"
export const USER_UPDATE_PROFILE_FAILED="USER_UPDATE_PROFILE_FAILED"
export const USER_PROFILE_RESET='USER_PROFILE_RESET'

export const USERLIST_REQUEST='USERLIST_REQUEST'
export const USERLIST_SUCCESS='USERLIST_SUCCESS'
export const USERLIST_FAILED='USERLIST_FAILED'

export const USER_DELETE_REQUEST='USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS='USER_DELETE_SUCCESS'
export const USER_DELETE_FAILED='USER_DELETE_FAILED'

export const ADMIN_UPDATE_USER_REQUEST='ADMIN_UPDATE_USER_REQUEST'
export const ADMIN_UPDATE_USER_SUCCESS='ADMIN_UPDATE_USER_SUCCESS'
export const ADMIN_UPDATE_USER_FAILED='ADMIN_UPDATE_USER_FAILED'
export const ADMIN_UPDATE_USER_RESET='ADMIN_UPDATE_USER_RESET'

export const USER_BY_ID_REQUEST='USER_BY_ID_REQUEST'
export const USER_BY_ID_SUCCESS='USER_BY_ID_SUCCESS'
export const USER_BY_ID_FAILED='USER_BY_ID_FAILED'
export const USER_BY_ID_RESET='USER_BY_ID_RESET'

